-- Example DuckDB queries for outputs generated by setup.sh.
--
-- Run from this directory:
--   duckdb -init queries.sql
--
-- Or paste individual queries into a DuckDB shell.

.mode duckbox
.headers on

SELECT
  claim_id,
  file_count,
  photo_count,
  document_count,
  review_task_count,
  claim_packet_status
FROM read_json_auto('workspace/quality-fixtures/outputs/claim_summary.jsonl');

SELECT
  task_type,
  priority,
  source_file_id,
  reason
FROM read_json_auto('workspace/quality-fixtures/outputs/review_tasks.jsonl')
ORDER BY priority, task_type, source_file_id;

SELECT
  file_id,
  decode_ok,
  quality_score,
  needs_review,
  issue_flags_json
FROM read_json_auto('workspace/quality-fixtures/outputs/photo_evidence.jsonl')
ORDER BY file_id;

SELECT
  metric_name,
  support,
  precision,
  recall,
  f1
FROM read_json_auto('workspace/quality-fixtures/outputs/photo_eval_metrics.jsonl');
